# Generated by Django 2.1.3 on 2018-11-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Psk',
        ),
        migrations.RemoveField(
            model_name='post',
            name='SSID',
        ),
    ]
