# Generated by Django 2.1.3 on 2018-12-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181130_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSID', models.CharField(max_length=50)),
                ('psk', models.CharField(max_length=50)),
                ('sIP', models.CharField(max_length=20)),
                ('netmask', models.CharField(max_length=20)),
                ('gateway', models.CharField(max_length=20)),
                ('networkIP', models.CharField(max_length=20)),
                ('broadcast', models.CharField(max_length=20)),
                ('dns_nameservers', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='dhcp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSID', models.CharField(max_length=50)),
                ('psk', models.CharField(max_length=50)),
            ],
        ),
    ]
